### ISSUE TITLE
Crash when `()` is used as Void

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#98]
The following code makes Sourcery crash

```swift
struct AnAction {
  typealias LoadingPayload = Request
  typealias CompletedPayload = CGRect
  typealias FailedPayload = ()
}
```

Workaround: Change `()` with `Void`

The code crashes here
```swift
            guard let alias = extract(tokens[index + 1], contents: contents),
                let type = extract(tokens[index + 2], contents: contents) else {
                    continue
            }
```
In `parseTypealiases`

It basically tries to access to a out of range index

Sourcery version: 0.5.0

**Comment by ilyapuchka** [comment]
@bolismauro I think I fixed that while working on #92

**Comment by bolismauro** [comment]
Yes I can confirm 👍 
Do you want me to close this or do you close it from #92?

**Comment by krzysztofzablocki** [comment]
keep it open until we merge it

**Comment by krzysztofzablocki** [comment]
@bolismauro can you try with `0.5.1` that I just released?

**Comment by bolismauro** [comment]
It seems that the bug is still there.
I'll investigate tomorrow and I'll try to give a min example of it (the project I'm using is private/very large)

**Comment by bolismauro** [comment]
it was an error in my configuration.
I can confirm it works. Amazing works as usual, thanks!
